# Generated by Django 4.2.21 on 2025-09-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data_fechamento',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginasweb.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('1', 'Em preparo'), ('2', 'Pronto para entrega'), ('3', 'Pronto para servir'), ('4', 'Enviado'), ('5', 'Cancelado'), ('6', 'Finalizado')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
