# Generated by Django 4.2.21 on 2025-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0002_alter_caixa_data_fechamento_alter_caixa_valor_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
