# Generated by Django 4.2.21 on 2025-09-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0003_alter_itens_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(help_text='Cor em formato hexadecimal, ex: #FF0000', max_length=7)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paginasweb.status'),
        ),
    ]
